name: A workflow for my Hello World file
on: push

jobs:
  build: Hello world action
    name: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
